name: Build Latest from Shared Workflow

on:
  push:
    branches: ["main", "feature/build-step"]

jobs:
  webpack_build:
    uses: ./.github/workflows/webpack_build.yml

  # get_public:
  #   needs: webpack_build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download public folder from webpack build
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: public-folder

  docker_build:
    needs: 
      - webpack_build
      # - get_public
    permissions:
      contents: read
      packages: write
    uses: Dartmouth-OpenAV/shared-workflows/.github/workflows/build_latest.yaml@main
    with:
      artifact-name: public-folder 
      artifact-path: './public'