name: Build Release from Shared Workflow

on:
  release:
    types: ["created"]

jobs:
  webpack_build:
    uses: ./.github/workflows/webpack_build.yml

  docker_build:
    needs: webpack_build
    permissions:
      contents: read
      packages: write
    uses: Dartmouth-OpenAV/shared-workflows/.github/workflows/build_release.yaml@main