name: Build Latest from Shared Workflow

on:
  push:
    branches: ["main"]

jobs:
  webpack_build:
    uses: ./.github/workflows/webpack_build.yml

  docker_build:
    needs: webpack_build
    permissions:
      contents: read
      packages: write
    uses: Dartmouth-OpenAV/shared-workflows/.github/workflows/build_latest.yaml@main
    with:
      artifact-name: public-folder 
      artifact-path: './public'