name: Build Latest from Shared Workflow

on:
  push:
    branches: ["main", "feature/build-step"]

jobs:
  webpack_build:
    uses: ./.github/workflows/webpack-build.yml

  docker_build:
    needs: webpack_build
    permissions:
      contents: read
      packages: write
    uses: Dartmouth-OpenAV/shared-workflows/.github/workflows/build_latest.yaml@main