name: Webpack Build

on: 
  workflow_call: {}

jobs: 
  webpack_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 'lts/*'
      
      - name: Install dependencies from package-lock.json
        run: npm ci --production=false

      - name: Run webpack build
        run: npm run build

      - name: Upload public folder
        uses: actions/upload-artifact@v4
        with: 
          name: public-folder
          path: public/